.TH GIT-TRIM 1
.SH NAME
git\-trim \- Automatically trims your tracking branches whose upstream branches are merged or stray.
.SH SYNOPSIS
\fBgit\-trim\fR [FLAGS] [OPTIONS]
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information

.TP
\fB\-\-no\-update\fR
Do not update remotes [config: trim.update]

.TP
\fB\-\-no\-confirm\fR
Do not ask confirm [config: trim.confirm]

.TP
\fB\-\-no\-detach\fR
Do not detach when HEAD is about to be deleted [config: trim.detach]

.TP
\fB\-\-dry\-run\fR
Do not delete branches, show what branches will be deleted
.SH OPTIONS
.TP
\fB\-b\fR, \fB\-\-bases\fR=\fIbases\fR
Comma separated multiple names of branches. All the other branches are compared with the upstream branches of those branches. [default: master] [config: trim.bases]

.TP
\fB\-p\fR, \fB\-\-protected\fR=\fIprotected\fR
Comma separated multiple glob patterns (e.g. `release\-*`, `feature/*`) of branches that should never be deleted. [default: <bases>] [config: trim.protected]

.TP
\fB\-\-update\-interval\fR=\fIupdate\-interval\fR
Prevents too frequent updates. Seconds between updates in seconds. 0 to disable. [default: 5] [config: trim.updateInterval]

.TP
\fB\-d\fR, \fB\-\-delete\fR=\fIdelete\fR
Comma separated values of `<filter unit>[:<remote name>]`. Filter unit is one of the `all, merged, gone, local, remote, merged\-local, merged\-remote, stray\-local, stray\-remote`. You can scope a filter unit to specific remote `:<remote name>` to a `filter unit` when the filter unit implies `merged\-remote` or `stray\-remote`. [default : `merged:origin`] [config: trim.filter]

If there are filter units that are scoped, it trims remote branches only in the specified remote. If there are any filter unit that isn`t scoped, it trims all remote branches.

`all` implies `merged\-local,merged\-remote,stray\-local,stray\-remote`. `merged` implies `merged\-local,merged\-remote`. `stray` implies `stray\-local,stray\-remote`. `local` implies `merged\-local,stray\-local`. `remote` implies `merged\-remote,stray\-remote`.
.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.

